services:
  - type: web
    name: samjoo-org-app
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && node init-db.js
    startCommand: node init-db.js && node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
