-- RightShip overlay (fills empty fields + new vessel_rightship table)
DROP TABLE IF EXISTS vessel_rightship;
CREATE TABLE vessel_rightship (
  imo                    TEXT PRIMARY KEY REFERENCES vessels(imo),
  doc_company            TEXT,
  commercial_manager     TEXT,
  technical_manager      TEXT,
  commercial_operator    TEXT,
  beneficial_owner       TEXT,
  registered_owner_rs    TEXT,
  hull_type              TEXT,
  statcode5              TEXT,
  age                    TEXT,
  lead_sister_ship       TEXT,
  status                 TEXT
);

INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('8606056','Doriko Ltd','Samjoo Maritime Co Ltd','Doriko Ltd','Samjoo Maritime Co Ltd','Samjoo Maritime Co Ltd','Astro Maritime Services SA','Double Bottom Entire Compartment Length','A35B2RV','38.5 y/o',NULL,'In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9021332','Doriko Ltd','Samjoo Maritime Co Ltd','Doriko Ltd','Samjoo Maritime Co Ltd','Samjoo Maritime Co Ltd','Young Shin Marine SA','Double Bottom Entire Compartment Length','A35B2RV','34.1 y/o','HEIJIN(8905426)','In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9053505','Doriko Ltd','Samjoo Maritime Co Ltd','Doriko Ltd','Samjoo Maritime Co Ltd','Samjoo Maritime Co Ltd','SC Marine SA','Double Bottom Entire Compartment Length','A35B2RV','32.2 y/o','JINGU(9021423)','In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9073701','Doriko Ltd','Samjoo Maritime Co Ltd','Doriko Ltd','Samjoo Maritime Co Ltd','Samjoo Maritime Co Ltd','Sang Shin Marine SA','Double Bottom Entire Compartment Length','A35B2RV','32 y/o','GRAND CHOICE(9169316)','In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9166704','Doriko Ltd','Samjoo Maritime Co Ltd','Doriko Ltd','Samjoo Maritime Co Ltd','Samjoo Maritime Co Ltd','Soo Shin Maritime SA','Double Bottom Partial Compartment Length','A35B3RV','27.4 y/o','SILVER SOUL(9153783)','In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9177430','Doriko Ltd','Doriko Ltd','Doriko Ltd','Samjoo Maritime Co Ltd','Unknown','SC Future SA','Double Bottom Entire Compartment Length','A35B2RV','27.2 y/o','DELPHINUS LEADER(9174282)','In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9304538','Samjoo SM Co Ltd','Samjoo Maritime Co Ltd','Samjoo SM Co Ltd','Samjoo Maritime Co Ltd','Samjoo Maritime Co Ltd','Samjoo Maritime Co Ltd','Double Bottom Entire Compartment Length','A21A2BC','20.7 y/o','ZEUS ONE(9258105)','In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9310678','Doriko Ltd','Woori Shipping Co Ltd','Doriko Ltd','Woori Shipping Co Ltd','Woori Shipping Co Ltd','Woori Shipping Co Ltd','Double Bottom Entire Compartment Length','A21A2BC','21.7 y/o','EAST HELIOS(9233387)','In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9418729','Doriko Ltd','Samjoo Marine Co Ltd','Doriko Ltd','Samjoo Marine Co Ltd','Samjoo Marine Co Ltd','Samjoo Marine Co Ltd','Double Bottom Entire Compartment Length','A21A2BC','17.4 y/o','KAMADIYA(9360013)','In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9445394','Doriko Ltd','Doriko Ltd','Doriko Ltd','Hyundai Glovis Co Ltd','Unknown','G Poseidon Corp','Double Bottom Entire Compartment Length','A35B2RV','15.1 y/o','DONG-A GLAUCOS(9441867)','In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9478511','Doriko Ltd','Samjoo Maritime Co Ltd','Doriko Ltd','Samjoo Maritime Co Ltd','Samjoo Maritime Co Ltd','Samjoo Maritime Co Ltd','Double Bottom Entire Compartment Length','A21A2BC','16.2 y/o','KAMADIYA(9360013)','In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9610561','Samjoo SM Co Ltd','Daebo L&S Co Ltd','Samjoo SM Co Ltd','Daebo L&S Co Ltd','Korea Ship Finance Co Ltd (KSF)','KSF Global No 31 SA','Double Bottom Entire Compartment Length','A21A2BC','12.4 y/o','LYRIC SUN(9586629)','In Trading Fleet');
INSERT INTO vessel_rightship (imo,doc_company,commercial_manager,technical_manager,commercial_operator,beneficial_owner,registered_owner_rs,hull_type,statcode5,age,lead_sister_ship,status) VALUES ('9710517','Samjoo SM Co Ltd','Samjoo SM Co Ltd','Samjoo SM Co Ltd','Daebo L&S Co Ltd','Korea Ship Finance Co Ltd (KSF)','KSF Global No 42 SA','Double Bottom Entire Compartment Length','A21A2BC','9.5 y/o','SPINEL(9644823)','In Trading Fleet');

-- Fill vessel_particulars empty fields with RightShip data
UPDATE vessel_particulars SET call_sign = '3FKQ7' WHERE imo = '8606056' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '373817000' WHERE imo = '8606056' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = '4451513B' WHERE imo = '8606056' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Panama' WHERE imo = '8606056' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Panama' WHERE imo = '8606056' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'London P&I' WHERE imo = '8606056' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Det Norske Veritas' WHERE imo = '8606056' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Vehicles Carrier' WHERE imo = '8606056' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '27/06/1986' WHERE imo = '8606056' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '30/10/1987' WHERE imo = '8606056' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'Astro Maritime Services SA' WHERE imo = '8606056' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Doriko Ltd' WHERE imo = '8606056' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Samjoo Maritime Co Ltd' WHERE imo = '8606056' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = '3ELP9' WHERE imo = '9021332' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '356005000' WHERE imo = '9021332' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = '2017792G' WHERE imo = '9021332' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Panama' WHERE imo = '9021332' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Panama' WHERE imo = '9021332' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'London P&I' WHERE imo = '9021332' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Nippon Kaiji Kyokai' WHERE imo = '9021332' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Vehicles Carrier' WHERE imo = '9021332' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '02/09/1991' WHERE imo = '9021332' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '13/03/1992' WHERE imo = '9021332' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'Young Shin Marine SA' WHERE imo = '9021332' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Doriko Ltd' WHERE imo = '9021332' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Samjoo Maritime Co Ltd' WHERE imo = '9021332' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = '3FWI3' WHERE imo = '9053505' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '352808000' WHERE imo = '9053505' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = '2126694G' WHERE imo = '9053505' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Panama' WHERE imo = '9053505' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Panama' WHERE imo = '9053505' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'Japan Ship Owners Mutual P&I' WHERE imo = '9053505' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Det Norske Veritas' WHERE imo = '9053505' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Vehicles Carrier' WHERE imo = '9053505' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '24/01/1992' WHERE imo = '9053505' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '27/01/1994' WHERE imo = '9053505' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'SC Marine SA' WHERE imo = '9053505' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Doriko Ltd' WHERE imo = '9053505' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Samjoo Maritime Co Ltd' WHERE imo = '9053505' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = '3FUX9' WHERE imo = '9073701' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '355297000' WHERE imo = '9073701' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = '4432812B' WHERE imo = '9073701' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Panama' WHERE imo = '9073701' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Panama' WHERE imo = '9073701' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'London P&I' WHERE imo = '9073701' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Det Norske Veritas' WHERE imo = '9073701' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Vehicles Carrier' WHERE imo = '9073701' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '03/09/1993' WHERE imo = '9073701' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '25/03/1994' WHERE imo = '9073701' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'Sang Shin Marine SA' WHERE imo = '9073701' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Doriko Ltd' WHERE imo = '9073701' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Samjoo Maritime Co Ltd' WHERE imo = '9073701' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = '3E3409' WHERE imo = '9166704' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '352001129' WHERE imo = '9166704' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = '54523PEXT' WHERE imo = '9166704' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Panama' WHERE imo = '9166704' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Panama' WHERE imo = '9166704' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'London P&I' WHERE imo = '9166704' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Det Norske Veritas' WHERE imo = '9166704' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Vehicles Carrier' WHERE imo = '9166704' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '09/05/1998' WHERE imo = '9166704' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '07/12/1998' WHERE imo = '9166704' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'Soo Shin Maritime SA' WHERE imo = '9166704' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Doriko Ltd' WHERE imo = '9166704' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Samjoo Maritime Co Ltd' WHERE imo = '9166704' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = '3FBO9' WHERE imo = '9177430' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '357170000' WHERE imo = '9177430' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = '2615799E' WHERE imo = '9177430' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Panama' WHERE imo = '9177430' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Panama' WHERE imo = '9177430' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'Japan Ship Owners Mutual P&I' WHERE imo = '9177430' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Det Norske Veritas' WHERE imo = '9177430' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Vehicles Carrier' WHERE imo = '9177430' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '02/04/1998' WHERE imo = '9177430' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '27/01/1999' WHERE imo = '9177430' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'SC Future SA' WHERE imo = '9177430' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Doriko Ltd' WHERE imo = '9177430' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Samjoo Maritime Co Ltd' WHERE imo = '9177430' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = 'D7MD' WHERE imo = '9304538' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '440467000' WHERE imo = '9304538' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = 'JJR-191070' WHERE imo = '9304538' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Korea, South' WHERE imo = '9304538' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Jeju' WHERE imo = '9304538' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'Japan Ship Owners Mutual P&I' WHERE imo = '9304538' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Korean Register' WHERE imo = '9304538' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Bulk Carrier' WHERE imo = '9304538' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '01/12/2004' WHERE imo = '9304538' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '26/07/2005' WHERE imo = '9304538' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'Samjoo Maritime Co Ltd' WHERE imo = '9304538' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Samjoo SM Co Ltd' WHERE imo = '9304538' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Samjoo Maritime Co Ltd' WHERE imo = '9304538' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = 'D7AP' WHERE imo = '9310678' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '440080000' WHERE imo = '9310678' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = 'JJR-211067' WHERE imo = '9310678' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Korea, South' WHERE imo = '9310678' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Jeju' WHERE imo = '9310678' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'London P&I' WHERE imo = '9310678' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Korean Register' WHERE imo = '9310678' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Bulk Carrier' WHERE imo = '9310678' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '21/04/2004' WHERE imo = '9310678' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '21/04/2004' WHERE imo = '9310678' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'Woori Shipping Co Ltd' WHERE imo = '9310678' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Doriko Ltd' WHERE imo = '9310678' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Woori Shipping Co Ltd' WHERE imo = '9310678' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = 'D7KH' WHERE imo = '9418729' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '440354000' WHERE imo = '9418729' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = 'JJR-241024' WHERE imo = '9418729' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Korea, South' WHERE imo = '9418729' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Jeju' WHERE imo = '9418729' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'London P&I' WHERE imo = '9418729' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Korean Register' WHERE imo = '9418729' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Bulk Carrier' WHERE imo = '9418729' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '30/10/2007' WHERE imo = '9418729' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '11/11/2008' WHERE imo = '9418729' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'Samjoo Marine Co Ltd' WHERE imo = '9418729' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Doriko Ltd' WHERE imo = '9418729' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Samjoo Marine Co Ltd' WHERE imo = '9418729' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = 'HP6652' WHERE imo = '9445394' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '354149000' WHERE imo = '9445394' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = '4278311B' WHERE imo = '9445394' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Panama' WHERE imo = '9445394' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Panama' WHERE imo = '9445394' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'Korea Shipowners Mutual P&I' WHERE imo = '9445394' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Det Norske Veritas' WHERE imo = '9445394' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Vehicles Carrier' WHERE imo = '9445394' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '10/05/2010' WHERE imo = '9445394' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '03/03/2011' WHERE imo = '9445394' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'G Poseidon Corp' WHERE imo = '9445394' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Doriko Ltd' WHERE imo = '9445394' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Hyundai Glovis Co Ltd' WHERE imo = '9445394' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = 'D7LH' WHERE imo = '9478511' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '440897000' WHERE imo = '9478511' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = 'JJR-241048' WHERE imo = '9478511' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Korea, South' WHERE imo = '9478511' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Jeju' WHERE imo = '9478511' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'London P&I' WHERE imo = '9478511' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Korean Register' WHERE imo = '9478511' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Bulk Carrier' WHERE imo = '9478511' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '25/08/2009' WHERE imo = '9478511' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '16/02/2010' WHERE imo = '9478511' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'Samjoo Maritime Co Ltd' WHERE imo = '9478511' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Doriko Ltd' WHERE imo = '9478511' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Samjoo Maritime Co Ltd' WHERE imo = '9478511' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = '3FIE9' WHERE imo = '9610561' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '354529000' WHERE imo = '9610561' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = '45274PEXT2' WHERE imo = '9610561' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Panama' WHERE imo = '9610561' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Panama' WHERE imo = '9610561' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'London P&I' WHERE imo = '9610561' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Korean Register' WHERE imo = '9610561' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Bulk Carrier' WHERE imo = '9610561' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '01/08/2013' WHERE imo = '9610561' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '10/12/2013' WHERE imo = '9610561' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'KSF Global No 31 SA' WHERE imo = '9610561' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Samjoo SM Co Ltd' WHERE imo = '9610561' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Daebo L&S Co Ltd' WHERE imo = '9610561' AND (operator IS NULL OR operator = '');
UPDATE vessel_particulars SET call_sign = '3E7848' WHERE imo = '9710517' AND (call_sign IS NULL OR call_sign = '');
UPDATE vessel_particulars SET mmsi = '352006244' WHERE imo = '9710517' AND (mmsi IS NULL OR mmsi = '');
UPDATE vessel_particulars SET official_no = '59757PEXT' WHERE imo = '9710517' AND (official_no IS NULL OR official_no = '');
UPDATE vessel_particulars SET flag = 'Panama' WHERE imo = '9710517' AND (flag IS NULL OR flag = '');
UPDATE vessel_particulars SET port_of_registry = 'Panama' WHERE imo = '9710517' AND (port_of_registry IS NULL OR port_of_registry = '');
UPDATE vessel_particulars SET p_and_i = 'London P&I' WHERE imo = '9710517' AND (p_and_i IS NULL OR p_and_i = '');
UPDATE vessel_particulars SET class_society = 'Korean Register' WHERE imo = '9710517' AND (class_society IS NULL OR class_society = '');
UPDATE vessel_particulars SET vessel_type = 'Bulk Carrier' WHERE imo = '9710517' AND (vessel_type IS NULL OR vessel_type = '');
UPDATE vessel_particulars SET keel_laid = '28/10/2015' WHERE imo = '9710517' AND (keel_laid IS NULL OR keel_laid = '');
UPDATE vessel_particulars SET built_year = '08/11/2016' WHERE imo = '9710517' AND (built_year IS NULL OR built_year = '');
UPDATE vessel_particulars SET owner = 'KSF Global No 42 SA' WHERE imo = '9710517' AND (owner IS NULL OR owner = '');
UPDATE vessel_particulars SET manager = 'Samjoo SM Co Ltd' WHERE imo = '9710517' AND (manager IS NULL OR manager = '');
UPDATE vessel_particulars SET operator = 'Daebo L&S Co Ltd' WHERE imo = '9710517' AND (operator IS NULL OR operator = '');